# Site settings
title: Sean's Blog
description: A personal blog powered by Jekyll and GitHub Pages
author: Sean
email: kimbh.mail@gmail.com
baseurl: "/sean-blog" # the subpath of your site, e.g. /blog
url: "" # your GitHub Pages URL will go here

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalink settings
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Social links (update with your links)
twitter_username: 
github_username: 

# Google Analytics (optional)
google_analytics: 

# Disqus Comments (optional)
disqus:
  shortname: 