# Site settings
title: Sean's Blog
description: A personal blog powered by Jekyll and GitHub Pages
author: Sean
email: kimbh.mail@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sean424.github.io" # your GitHub Pages URL

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalink settings
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Social links (update with your links)
twitter_username: 
github_username: 

# Google Analytics (optional)
google_analytics: 

# Disqus Comments (optional)
disqus:
  shortname: 