baseURL: "https://sean424.github.io/" 
title: Sean Kim
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact
          url: contact/
          weight: 4

params:
    description: "Sean Kim - Researcher in Machine Learning and Computational Biology"
    author: Sean Kim
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["posts","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sean Kim
          subtitle: "Researcher in Machine Learning and Computational Biology. I develop innovative computational methods to understand complex biological systems through advanced machine learning techniques."
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About
              url: about/
            - name: Projects
              url: projects/
            - name: Blog
              url: posts/
            - name: Publications
              url: https://scholar.google.com/citations?hl=en&user=QsD73G4AAAAJ
            - name: Contact
              url: contact/

    socialIcons:
        - name: Email
          url: mailto:kimbh.mail@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=QsD73G4AAAAJ
        - name: GitHub
          url: https://github.com/sean424

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2